# Generated by Django 2.1.1 on 2018-10-08 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 10, 8, 4, 3, 33, 401771, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
