# Generated by Django 2.1.1 on 2018-10-08 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181008_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 10, 8, 6, 56, 39, 114803, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
